/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import Lista.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PROPIETARIO
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    private Nodo listaCliente;
    private Lista lista;
    private DefaultTableModel modelo;
    private String []datos = new String[6];
    private int filaModificar;
    public Ventana() {
        initComponents();
        estadosTextos(false);
        botones(btnAgregar.getText(), false);
        lista = new Lista();
        
        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección: "));
        txtDni.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI: "));
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail"));
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));
        
        modelo = new DefaultTableModel();
        modelo.addColumn("#");
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("EMAIL");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("TELEFONO");
        
        tabla.setModel(modelo);
        
    }
    public void modificarTextos(String Direccion, String Dni, String Email, String nombre, String telefono){
        txtDireccion.setText(Direccion);
        txtDni.setText(Dni);
        txtEmail.setText(Email);
        txtNombre.setText(nombre);
        txtTelefono.setText(telefono);
    }
    public void estadosTextos(Boolean valor){
        txtDireccion.setEditable(valor);
        txtDni.setEditable(valor);
        txtEmail.setEditable(valor);
        txtNombre.setEditable(valor);
        txtTelefono.setEditable(valor);
    }
    public void botones(String boton, Boolean valor){
        switch (boton){
            case "AGREGAR":
                btnEliminar.setEnabled(valor);
                btnListar.setEnabled(valor);
                btnModificar.setEnabled(valor);
                break;
            case "ELIMINAR":
                btnAgregar.setEnabled(valor);
                btnListar.setEnabled(valor);
                btnModificar.setEnabled(valor);
                break;
            case "MODIFICAR":
                btnAgregar.setEnabled(valor);
                btnListar.setEnabled(valor);
                btnEliminar.setEnabled(valor);
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(txtDni)
                    .addComponent(txtNombre)
                    .addComponent(txtDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addGap(13, 13, 13)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(btnAgregar.getText().equals("AGREGAR")){
            estadosTextos(true);
            botones(btnAgregar.getText(), false);
            btnAgregar.setText("GUARDAR");
        }else{
           Persona usuario = new Persona(txtDireccion.getText(), txtDni.getText(), txtEmail.getText(), txtTelefono.getText(), txtNombre.getText());
        
            lista.insertarFinal(usuario);
            btnAgregar.setText("AGREGAR");
            estadosTextos(false);
            botones(btnAgregar.getText(), true);
            modificarTextos("", "", "", "", ""); 
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        listaCliente = lista.getTop();
        
        modelo.setRowCount(0);
        int cantidad = 1;
        while( listaCliente != null ){
            datos[0] = Integer.toString(cantidad);
            datos[1] = listaCliente.getDni();
            datos[2] = listaCliente.getNombre();
            datos[3] = listaCliente.getEmail();
            datos[4] = listaCliente.getDireccion();
            datos[5] = listaCliente.getTelefono();
            
            modelo.addRow(datos);
            
            cantidad ++;
            
            listaCliente = listaCliente.getSiguiente();
            
        }
        
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(lista.getCantidad()!=0){
            listaCliente = lista.getTop();
            if(btnModificar.getText().equals("MODIFICAR")){
                filaModificar = Integer.parseInt(JOptionPane.showInputDialog("Introduzca numero de la fila: "));
                if(!(filaModificar >= 0 && filaModificar <= lista.getCantidad())) return;
                estadosTextos(true);
                botones(btnModificar.getText(), false);
                int fila = 1;

                while(listaCliente != null){
                    if(fila == filaModificar) break;
                    fila++;
                    listaCliente = listaCliente.getSiguiente();

                }

                modificarTextos(listaCliente.getDireccion(), listaCliente.getDni(), 
                        listaCliente.getEmail(), listaCliente.getNombre(), listaCliente.getTelefono());

                btnModificar.setText("GUARDAR");

            }else{

                Nodo nuevo = new Nodo();

                nuevo.setDireccion(txtDireccion.getText());
                nuevo.setDni(txtDni.getText());
                nuevo.setEmail(txtEmail.getText());
                nuevo.setNombre(txtNombre.getText());
                nuevo.setTelefono(txtTelefono.getText());

                lista.modificar(filaModificar, nuevo);
                modificarTextos("", "", "", "", "");
                btnModificar.setText("MODIFICAR");
                estadosTextos(false);
                botones(btnModificar.getText(), true);

            }
        }else{
            JOptionPane.showMessageDialog(Ventana.this, "esta vacio!!!");
            btnModificar.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
 
        if(lista.getCantidad()!=0){
            
            int fila = Integer.parseInt(JOptionPane.showInputDialog("Introduzca numero de la fila: "));
            if(fila >= 1 && fila <= lista.getCantidad()){
                botones(btnEliminar.getText(), false);
                lista.eliminar(fila);
                botones(btnEliminar.getText(), true);
            }else JOptionPane.showMessageDialog(Ventana.this, "numero invalido");
            
        }else{
            
            JOptionPane.showMessageDialog(Ventana.this, "esta vacio!!!");
            btnEliminar.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
