SET SERVEROUTPUT ON;
--EJERCICIO
--DADO UN NUMERO, DEVOLVER EL DOBLE SI EL NUMERO NO ES PAR; CASO CONTRARIO EL TRIPLE.
DECLARE
    NUMERO NUMBER := 1;
BEGIN
    IF NOT MOD(NUMERO,2) = 0 THEN
        DBMS_OUTPUT.PUT_LINE(NUMERO*2);
    ELSE
        DBMS_OUTPUT.PUT_LINE(NUMERO*3);
    END IF;
END;