SET SERVEROUTPUT ON;
--EJERCICIO 4
--DETERMINAR SI UN NUMERO ENTERO ES PAR O IMPAR;
DECLARE
    NUMERO NUMBER := -2;
BEGIN
    IF NUMERO = 0 THEN
        DBMS_OUTPUT.PUT_LINE('EL CERO NO ES PAR NI IMPAR');
    ELSIF MOD(NUMERO,2) = 0 THEN
        DBMS_OUTPUT.PUT_LINE('ES PAR');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('ES IMPAR');
    END IF;
END;