/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

import javax.swing.ButtonGroup;

/**
 *
 * @author PROPIETARIO
 */
public class radiobuton extends javax.swing.JFrame {

    /**
     * Creates new form radiobuton
     */
    objeto obj;
    public radiobuton() {
        initComponents();
        txtRadio.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrese radio"));
        
        ButtonGroup btngrupo=new ButtonGroup();
        jrbArea.setSelected(true);
        btngrupo.add(jrbArea);
        btngrupo.add(jrbPerimetro);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbArea = new javax.swing.JRadioButton();
        jrbPerimetro = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        txtRadio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrbArea.setText("Area");
        jrbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAreaActionPerformed(evt);
            }
        });

        jrbPerimetro.setText("Perimetro");
        jrbPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPerimetroActionPerformed(evt);
            }
        });

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        btnLimpiar.setText("Limpiar");

        txtRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbPerimetro)
                    .addComponent(jrbArea)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jrbArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbPerimetro)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAreaActionPerformed
        // TODO add your handling code here:
        if ( this.jrbArea.isSelected()){
            if ( txtRadio.getText().equals("")){
                obj = new objeto();
                txtMostrar.setText("EL area es: " + obj.Area(obj.getRadio()) );
                
            }
            else{
                obj = new objeto(Double.parseDouble(txtRadio.getText()));
                txtMostrar.setText("el are es: "+ obj.Area(obj.getRadio()));
            }
        }else txtMostrar.setText(null);
    }//GEN-LAST:event_jrbAreaActionPerformed

    private void txtRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRadioActionPerformed

    private void jrbPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPerimetroActionPerformed
        // TODO add your handling code here:
        if ( this.jrbPerimetro.isSelected()){
            if ( txtRadio.getText().equals("")){
                obj = new objeto();
                txtMostrar.setText("EL perimetro es: " + obj.Perimetro(obj.getRadio()));
                
            }
            else{
                obj = new objeto(Double.parseDouble(txtRadio.getText()));
                txtMostrar.setText("el perimetro es: "+ obj.Perimetro(obj.getRadio()));
            }
        }else txtMostrar.setText(null);
    }//GEN-LAST:event_jrbPerimetroActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbArea;
    private javax.swing.JRadioButton jrbPerimetro;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
