/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariofutbol;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PROPIETARIO
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    
    DefaultListModel lstmodel;
    
    public ventana() {
        initComponents();
        
        lstmodel = new DefaultListModel();
        
        txtAgregarJugador.setBorder(javax.swing.BorderFactory.createTitledBorder("INSERTE JUGADOR"));
        txtAgregarEntrenador.setBorder(javax.swing.BorderFactory.createTitledBorder("INSERTE ENTRENADOR"));
        txtAgregarMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("INSERTE MASAJISTA"));
        txtAgregarViaje.setBorder(javax.swing.BorderFactory.createTitledBorder("INSERTE VIAJE"));
        
        lstJugadores.setModel(lstmodel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAgregarJugador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstJugadores = new javax.swing.JList<>();
        btnAgregarJugador = new javax.swing.JButton();
        btnEliminarJugador = new javax.swing.JButton();
        btnModificarJugador = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtAgregarEntrenador = new javax.swing.JTextField();
        cbEntrenador = new javax.swing.JComboBox<>();
        btnEntrenador = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtAgregarMasajista = new javax.swing.JTextField();
        btnMasajista = new javax.swing.JButton();
        cbMasajista = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        txtAgregarViaje = new javax.swing.JTextField();
        cbViajes = new javax.swing.JComboBox<>();
        btnViaje = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnExit = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarJugadorActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstJugadores);

        btnAgregarJugador.setText("Agregar Jugador");
        btnAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJugadorActionPerformed(evt);
            }
        });

        btnEliminarJugador.setText("Eliminar Jugador");
        btnEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJugadorActionPerformed(evt);
            }
        });

        btnModificarJugador.setText("Modificar Jugador");
        btnModificarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarJugadorActionPerformed(evt);
            }
        });

        txtAgregarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarEntrenadorActionPerformed(evt);
            }
        });

        btnEntrenador.setText("Agregar Entrenador");
        btnEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrenadorActionPerformed(evt);
            }
        });

        txtAgregarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarMasajistaActionPerformed(evt);
            }
        });

        btnMasajista.setText("Agregar Masajista");
        btnMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasajistaActionPerformed(evt);
            }
        });

        txtAgregarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarViajeActionPerformed(evt);
            }
        });

        btnViaje.setText("Agregar Viaje");
        btnViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajeActionPerformed(evt);
            }
        });

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtAgregarJugador)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnAgregarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnEliminarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnModificarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbEntrenador, 0, 259, Short.MAX_VALUE)
                                            .addComponent(txtAgregarEntrenador))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEntrenador))))
                            .addComponent(cbViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtAgregarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnViaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtAgregarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnMasajista)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarJugador))
                    .addComponent(txtAgregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModificarJugador)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAgregarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEntrenador))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAgregarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMasajista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAgregarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarJugadorActionPerformed

    
    private void btnAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJugadorActionPerformed
        // TODO add your handling code here:
        
        lstmodel.addElement(txtAgregarJugador.getText());
        
        txtAgregarJugador.setText("");
        txtAgregarJugador.requestFocus();
        
    }//GEN-LAST:event_btnAgregarJugadorActionPerformed

    private void btnModificarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarJugadorActionPerformed
        // TODO add your handling code here:
        lstmodel.setElementAt(JOptionPane.showInputDialog("¿Inserte el nombre?"), Integer.parseInt(JOptionPane.showInputDialog("¿ingrese el numero de orden que quiere eliminar?"))-1);
    }//GEN-LAST:event_btnModificarJugadorActionPerformed

    private void btnEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJugadorActionPerformed
        // TODO add your handling code here:
        lstmodel.remove(Integer.parseInt(JOptionPane.showInputDialog("¿ingrese el numero de orden que quiere eliminar?"))-1);
    }//GEN-LAST:event_btnEliminarJugadorActionPerformed

    private void txtAgregarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarEntrenadorActionPerformed

    private void btnEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrenadorActionPerformed
        // TODO add your handling code here:
        cbEntrenador.addItem(txtAgregarEntrenador.getText());
        txtAgregarEntrenador.setText("");
        txtAgregarEntrenador.requestFocus();
    }//GEN-LAST:event_btnEntrenadorActionPerformed

    private void txtAgregarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarMasajistaActionPerformed

    private void btnMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasajistaActionPerformed
        // TODO add your handling code here:
        cbMasajista.addItem(txtAgregarMasajista.getText());
        txtAgregarMasajista.setText("");
        txtAgregarMasajista.requestFocus();
    }//GEN-LAST:event_btnMasajistaActionPerformed

    private void txtAgregarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarViajeActionPerformed

    private void btnViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajeActionPerformed
        // TODO add your handling code here:
        cbViajes.addItem(txtAgregarViaje.getText());
        txtAgregarViaje.setText("");
        txtAgregarViaje.requestFocus();
    }//GEN-LAST:event_btnViajeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String mensaje = String.format( "el jugador %s, tiene como entrenador a %s, "
                + "le toca el masaje con %s y debe viajar a %s", lstmodel.getElementAt(lstJugadores.getSelectedIndex()), 
                cbEntrenador.getSelectedItem(), cbMasajista.getSelectedItem(), cbViajes.getSelectedItem());
        
        JOptionPane.showMessageDialog(ventana.this, mensaje);
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnEntrenador;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMasajista;
    private javax.swing.JButton btnModificarJugador;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnViaje;
    private javax.swing.JComboBox<String> cbEntrenador;
    private javax.swing.JComboBox<String> cbMasajista;
    private javax.swing.JComboBox<String> cbViajes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JList<String> lstJugadores;
    private javax.swing.JTextField txtAgregarEntrenador;
    private javax.swing.JTextField txtAgregarJugador;
    private javax.swing.JTextField txtAgregarMasajista;
    private javax.swing.JTextField txtAgregarViaje;
    // End of variables declaration//GEN-END:variables
}
