/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariofutbol;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PROPIETARIO
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    
    DefaultListModel lstmodel;
    Futbolista Fut;
    Masajista Mas;
    Entrenador ent;
    public ventana() {
        initComponents();
        
        lstmodel = new DefaultListModel();
        
        txtNombreFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtApellidoFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));
        txtEdadFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("EDAD"));
        txtDorsalFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("DORSAL"));
        txtDemarcacionFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("DEMARCACION"));
        txtAJugador.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTA DE JUGADORES"));
        
        txtNombreEntrenador.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtApellidoEntrenador.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));
        txtEdadEntrenador.setBorder(javax.swing.BorderFactory.createTitledBorder("EDAD"));
        txtIdFederacion.setBorder(javax.swing.BorderFactory.createTitledBorder("ID FEDERACIÓN"));
        
        txtNombreMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtApellidoMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));
        txtEdadMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("EDAD"));
        txtTituloMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("TITULACIÓN"));
        txtAniosExperiencia.setBorder(javax.swing.BorderFactory.createTitledBorder("AÑOS EXP."));
        
        txtAgregarViaje.setBorder(javax.swing.BorderFactory.createTitledBorder("INSERTE VIAJE"));
        
        txtAJugador.setModel(lstmodel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreFutbolista = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAJugador = new javax.swing.JList<>();
        btnAgregarJugador = new javax.swing.JButton();
        btnEliminarJugador = new javax.swing.JButton();
        btnModificarJugador = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreEntrenador = new javax.swing.JTextField();
        cbEntrenador = new javax.swing.JComboBox<>();
        cbMasajista = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        txtAgregarViaje = new javax.swing.JTextField();
        cbViajes = new javax.swing.JComboBox<>();
        btnViaje = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        txtApellidoFutbolista = new javax.swing.JTextField();
        txtEdadFutbolista = new javax.swing.JTextField();
        txtDemarcacionFutbolista = new javax.swing.JTextField();
        txtDorsalFutbolista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreMasajista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoEntrenador = new javax.swing.JTextField();
        txtEdadEntrenador = new javax.swing.JTextField();
        txtIdFederacion = new javax.swing.JTextField();
        btnModificarEntrenador = new javax.swing.JButton();
        btnAgregarEntrenador = new javax.swing.JButton();
        btnEliminarEntrenador = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoMasajista = new javax.swing.JTextField();
        txtEdadMasajista = new javax.swing.JTextField();
        txtTituloMasajista = new javax.swing.JTextField();
        txtAniosExperiencia = new javax.swing.JTextField();
        btnModificarMasajista = new javax.swing.JButton();
        btnAgregarMasajista = new javax.swing.JButton();
        btnEliminarMasajista = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombreFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreFutbolistaActionPerformed(evt);
            }
        });

        txtAJugador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txtAJugador);

        btnAgregarJugador.setText("AGREGAR");
        btnAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJugadorActionPerformed(evt);
            }
        });

        btnEliminarJugador.setText("ELIMINAR");
        btnEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJugadorActionPerformed(evt);
            }
        });

        btnModificarJugador.setText("MODIFICAR");
        btnModificarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarJugadorActionPerformed(evt);
            }
        });

        txtNombreEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEntrenadorActionPerformed(evt);
            }
        });

        txtAgregarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarViajeActionPerformed(evt);
            }
        });

        btnViaje.setText("Agregar Viaje");
        btnViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajeActionPerformed(evt);
            }
        });

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        txtApellidoFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoFutbolistaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATOS DEL ENTRENADOR");

        txtNombreMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMasajistaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DATOS DEL JUGADOR");

        txtApellidoEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoEntrenadorActionPerformed(evt);
            }
        });

        btnModificarEntrenador.setText("MODIFICAR");
        btnModificarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEntrenadorActionPerformed(evt);
            }
        });

        btnAgregarEntrenador.setText("AGREGAR");
        btnAgregarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEntrenadorActionPerformed(evt);
            }
        });

        btnEliminarEntrenador.setText("ELIMINAR");
        btnEliminarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEntrenadorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("DATOS DE LA MASAJISTA");

        txtApellidoMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMasajistaActionPerformed(evt);
            }
        });

        txtAniosExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAniosExperienciaActionPerformed(evt);
            }
        });

        btnModificarMasajista.setText("MODIFICAR");
        btnModificarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMasajistaActionPerformed(evt);
            }
        });

        btnAgregarMasajista.setText("AGREGAR");
        btnAgregarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMasajistaActionPerformed(evt);
            }
        });

        btnEliminarMasajista.setText("ELIMINAR");
        btnEliminarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMasajistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEdadFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDorsalFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDemarcacionFutbolista))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNombreFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellidoFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAgregarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(btnModificarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator5))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtApellidoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtEdadEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtIdFederacion)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnModificarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAgregarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnViaje))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(258, 258, 258))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtApellidoMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtEdadMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTituloMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAniosExperiencia)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnModificarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAgregarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(cbMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidoFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdadFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDorsalFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDemarcacionFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFederacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbMasajista, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAgregarMasajista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAniosExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAgregarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViaje))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrar)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreFutbolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFutbolistaActionPerformed

    
    public void insertarFutbolista(){
        Fut = new Futbolista(1, txtNombreFutbolista.getText(), txtApellidoFutbolista.getText(), Integer.parseInt(txtEdadFutbolista.getText()), Integer.parseInt(txtDorsalFutbolista.getText()), txtDemarcacionFutbolista.getText());
        
    }
    
    private void btnAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJugadorActionPerformed
        // TODO add your handling code here:
        insertarFutbolista();
        lstmodel.addElement(Fut.getApellido()+", "+Fut.getNombre());
        
        txtNombreFutbolista.setText("");
        txtApellidoFutbolista.setText("");
        txtEdadFutbolista.setText("");
        txtDorsalFutbolista.setText("");
        txtDemarcacionFutbolista.setText("");
        txtNombreFutbolista.requestFocus();
        
    }//GEN-LAST:event_btnAgregarJugadorActionPerformed

    private void btnModificarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarJugadorActionPerformed
        // TODO add your handling code here:
        lstmodel.setElementAt(JOptionPane.showInputDialog("¿Inserte el nombre?"), Integer.parseInt(JOptionPane.showInputDialog("¿ingrese el numero de orden que quiere eliminar?"))-1);
    }//GEN-LAST:event_btnModificarJugadorActionPerformed

    private void btnEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJugadorActionPerformed
        // TODO add your handling code here:
        lstmodel.remove(Integer.parseInt(JOptionPane.showInputDialog("¿ingrese el numero de orden que quiere eliminar?"))-1);
    }//GEN-LAST:event_btnEliminarJugadorActionPerformed

    private void txtNombreEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEntrenadorActionPerformed

    private void txtAgregarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarViajeActionPerformed

    private void btnViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajeActionPerformed
        // TODO add your handling code here:
        cbViajes.addItem(txtAgregarViaje.getText());
        txtAgregarViaje.setText("");
        txtAgregarViaje.requestFocus();
    }//GEN-LAST:event_btnViajeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String mensaje = String.format( "el jugador %s, tiene como entrenador a %s, "
                + "le toca el masaje con %s y debe viajar a %s", lstmodel.getElementAt(txtAJugador.getSelectedIndex()), 
                cbEntrenador.getSelectedItem(), cbMasajista.getSelectedItem(), cbViajes.getSelectedItem());
        
        JOptionPane.showMessageDialog(ventana.this, mensaje);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txtApellidoFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoFutbolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoFutbolistaActionPerformed

    private void txtNombreMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMasajistaActionPerformed

    private void txtApellidoEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoEntrenadorActionPerformed

    private void btnModificarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarEntrenadorActionPerformed

    public void datosEntrenador(){
        ent = new Entrenador(txtIdFederacion.getText(), 1, txtNombreEntrenador.getText(), txtApellidoEntrenador.getText(), Integer.parseInt(txtEdadEntrenador.getText()));
       
    }
    private void btnAgregarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEntrenadorActionPerformed
        // TODO add your handling code here:
        datosEntrenador();
        cbEntrenador.addItem(ent.getApellido()+", "+ent.getNombre());
        txtNombreEntrenador.setText("");
        txtApellidoEntrenador.setText("");
        txtEdadEntrenador.setText("");
        txtIdFederacion.setText("");
        txtNombreEntrenador.requestFocus();
    }//GEN-LAST:event_btnAgregarEntrenadorActionPerformed

    private void btnEliminarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEntrenadorActionPerformed

    private void txtApellidoMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMasajistaActionPerformed

    private void btnModificarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMasajistaActionPerformed

    public void datosMasajista(){
        Mas = new Masajista(txtTituloMasajista.getText(), Integer.parseInt(txtAniosExperiencia.getText()), 1, txtNombreMasajista.getText(), txtApellidoMasajista.getText(), Integer.parseInt(txtEdadMasajista.getText()));
    } 
            
    private void btnAgregarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMasajistaActionPerformed
        // TODO add your handling code here:
        datosMasajista();
        cbMasajista.addItem(Mas.getApellido()+", "+Mas.getNombre());
        txtNombreMasajista.setText("");
        txtApellidoMasajista.setText("");
        txtEdadMasajista.setText("");
        txtTituloMasajista.setText("");
        txtAniosExperiencia.setText("");
        txtNombreEntrenador.requestFocus();
    }//GEN-LAST:event_btnAgregarMasajistaActionPerformed

    private void btnEliminarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMasajistaActionPerformed

    private void txtAniosExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAniosExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAniosExperienciaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEntrenador;
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnAgregarMasajista;
    private javax.swing.JButton btnEliminarEntrenador;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnEliminarMasajista;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModificarEntrenador;
    private javax.swing.JButton btnModificarJugador;
    private javax.swing.JButton btnModificarMasajista;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnViaje;
    private javax.swing.JComboBox<String> cbEntrenador;
    private javax.swing.JComboBox<String> cbMasajista;
    private javax.swing.JComboBox<String> cbViajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JList<String> txtAJugador;
    private javax.swing.JTextField txtAgregarViaje;
    private javax.swing.JTextField txtAniosExperiencia;
    private javax.swing.JTextField txtApellidoEntrenador;
    private javax.swing.JTextField txtApellidoFutbolista;
    private javax.swing.JTextField txtApellidoMasajista;
    private javax.swing.JTextField txtDemarcacionFutbolista;
    private javax.swing.JTextField txtDorsalFutbolista;
    private javax.swing.JTextField txtEdadEntrenador;
    private javax.swing.JTextField txtEdadFutbolista;
    private javax.swing.JTextField txtEdadMasajista;
    private javax.swing.JTextField txtIdFederacion;
    private javax.swing.JTextField txtNombreEntrenador;
    private javax.swing.JTextField txtNombreFutbolista;
    private javax.swing.JTextField txtNombreMasajista;
    private javax.swing.JTextField txtTituloMasajista;
    // End of variables declaration//GEN-END:variables
}
