/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariofutbol;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author PROPIETARIO
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    
    DefaultListModel lstmodel;
    Futbolista Fut;
    Masajista Mas;
    Entrenador ent;
    public ventana() {
        initComponents();
        
        btnModificarJugador.setEnabled(false);
        btnEliminarJugador.setEnabled(false);
        
        btnModificarEntrenador.setEnabled(false);
        btnEliminarEntrenador.setEnabled(false);
        
        btnModificarMasajista.setEnabled(false);
        btnEliminarMasajista.setEnabled(false);
        
        txtAgregarViaje.setEditable(false);
        txtAniosExperiencia.setEditable(false);
        txtApellidoEntrenador.setEditable(false);
        txtApellidoFutbolista.setEditable(false);
        txtApellidoMasajista.setEditable(false);
        txtDemarcacionFutbolista.setEditable(false);
        txtDorsalFutbolista.setEditable(false);
        txtEdadEntrenador.setEditable(false);
        txtEdadFutbolista.setEditable(false);
        txtEdadMasajista.setEditable(false);
        txtIdFederacion.setEditable(false);
        txtNombreEntrenador.setEditable(false);
        txtNombreFutbolista.setEditable(false);
        txtNombreMasajista.setEditable(false);
        txtTituloMasajista.setEditable(false);
        
        lstmodel = new DefaultListModel();
        
        txtNombreFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtApellidoFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));
        txtEdadFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("EDAD"));
        txtDorsalFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("DORSAL"));
        txtDemarcacionFutbolista.setBorder(javax.swing.BorderFactory.createTitledBorder("DEMARCACION"));
        txtAJugador.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTA DE JUGADORES"));
        
        txtNombreEntrenador.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtApellidoEntrenador.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));
        txtEdadEntrenador.setBorder(javax.swing.BorderFactory.createTitledBorder("EDAD"));
        txtIdFederacion.setBorder(javax.swing.BorderFactory.createTitledBorder("ID FEDERACIÓN"));
        
        txtNombreMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMBRE"));
        txtApellidoMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("APELLIDO"));
        txtEdadMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("EDAD"));
        txtTituloMasajista.setBorder(javax.swing.BorderFactory.createTitledBorder("TITULACIÓN"));
        txtAniosExperiencia.setBorder(javax.swing.BorderFactory.createTitledBorder("AÑOS EXP."));
        
        txtAgregarViaje.setBorder(javax.swing.BorderFactory.createTitledBorder("INSERTE VIAJE"));
        
        txtAJugador.setModel(lstmodel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreFutbolista = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAJugador = new javax.swing.JList<>();
        btnAgregarJugador = new javax.swing.JButton();
        btnEliminarJugador = new javax.swing.JButton();
        btnModificarJugador = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreEntrenador = new javax.swing.JTextField();
        cbEntrenador = new javax.swing.JComboBox<>();
        cbMasajista = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        txtAgregarViaje = new javax.swing.JTextField();
        cbViajes = new javax.swing.JComboBox<>();
        btnViaje = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        txtApellidoFutbolista = new javax.swing.JTextField();
        txtEdadFutbolista = new javax.swing.JTextField();
        txtDemarcacionFutbolista = new javax.swing.JTextField();
        txtDorsalFutbolista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreMasajista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoEntrenador = new javax.swing.JTextField();
        txtEdadEntrenador = new javax.swing.JTextField();
        txtIdFederacion = new javax.swing.JTextField();
        btnModificarEntrenador = new javax.swing.JButton();
        btnAgregarEntrenador = new javax.swing.JButton();
        btnEliminarEntrenador = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoMasajista = new javax.swing.JTextField();
        txtEdadMasajista = new javax.swing.JTextField();
        txtTituloMasajista = new javax.swing.JTextField();
        txtAniosExperiencia = new javax.swing.JTextField();
        btnModificarMasajista = new javax.swing.JButton();
        btnAgregarMasajista = new javax.swing.JButton();
        btnEliminarMasajista = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombreFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreFutbolistaActionPerformed(evt);
            }
        });
        txtNombreFutbolista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreFutbolistaKeyTyped(evt);
            }
        });

        txtAJugador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(txtAJugador);

        btnAgregarJugador.setText("AGREGAR");
        btnAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJugadorActionPerformed(evt);
            }
        });

        btnEliminarJugador.setText("ELIMINAR");
        btnEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJugadorActionPerformed(evt);
            }
        });

        btnModificarJugador.setText("MODIFICAR");
        btnModificarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarJugadorActionPerformed(evt);
            }
        });

        txtNombreEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEntrenadorActionPerformed(evt);
            }
        });
        txtNombreEntrenador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEntrenadorKeyTyped(evt);
            }
        });

        txtAgregarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarViajeActionPerformed(evt);
            }
        });
        txtAgregarViaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarViajeKeyTyped(evt);
            }
        });

        btnViaje.setText("AGREGAR VIAJE");
        btnViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajeActionPerformed(evt);
            }
        });

        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        txtApellidoFutbolista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoFutbolistaActionPerformed(evt);
            }
        });
        txtApellidoFutbolista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoFutbolistaKeyTyped(evt);
            }
        });

        txtEdadFutbolista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadFutbolistaKeyTyped(evt);
            }
        });

        txtDemarcacionFutbolista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDemarcacionFutbolistaKeyTyped(evt);
            }
        });

        txtDorsalFutbolista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDorsalFutbolistaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATOS DEL ENTRENADOR");

        txtNombreMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMasajistaActionPerformed(evt);
            }
        });
        txtNombreMasajista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreMasajistaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("DATOS DEL FUTBOLISTA");

        txtApellidoEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoEntrenadorActionPerformed(evt);
            }
        });
        txtApellidoEntrenador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoEntrenadorKeyTyped(evt);
            }
        });

        txtEdadEntrenador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadEntrenadorKeyTyped(evt);
            }
        });

        txtIdFederacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdFederacionKeyTyped(evt);
            }
        });

        btnModificarEntrenador.setText("MODIFICAR");
        btnModificarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEntrenadorActionPerformed(evt);
            }
        });

        btnAgregarEntrenador.setText("AGREGAR");
        btnAgregarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEntrenadorActionPerformed(evt);
            }
        });

        btnEliminarEntrenador.setText("ELIMINAR");
        btnEliminarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEntrenadorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("DATOS DE LA MASAJISTA");

        txtApellidoMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMasajistaActionPerformed(evt);
            }
        });
        txtApellidoMasajista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMasajistaKeyTyped(evt);
            }
        });

        txtEdadMasajista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadMasajistaKeyTyped(evt);
            }
        });

        txtTituloMasajista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloMasajistaKeyTyped(evt);
            }
        });

        txtAniosExperiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAniosExperienciaActionPerformed(evt);
            }
        });
        txtAniosExperiencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAniosExperienciaKeyTyped(evt);
            }
        });

        btnModificarMasajista.setText("MODIFICAR");
        btnModificarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMasajistaActionPerformed(evt);
            }
        });

        btnAgregarMasajista.setText("AGREGAR");
        btnAgregarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMasajistaActionPerformed(evt);
            }
        });

        btnEliminarMasajista.setText("ELIMINAR");
        btnEliminarMasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMasajistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAgregarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViaje)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(258, 258, 258))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEdadFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDorsalFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDemarcacionFutbolista))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNombreFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellidoFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAgregarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                        .addComponent(btnModificarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jSeparator5))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtApellidoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtEdadEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtIdFederacion)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnModificarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAgregarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtApellidoMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtEdadMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTituloMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAniosExperiencia)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnModificarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnEliminarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAgregarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(cbMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap(2, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidoFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdadFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDorsalFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDemarcacionFutbolista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdFederacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbMasajista, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAgregarMasajista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdadMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAniosExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarMasajista, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbViajes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAgregarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreFutbolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFutbolistaActionPerformed

    
    public void insertarFutbolista(){
        Fut = new Futbolista(Futbolista.id+1, txtNombreFutbolista.getText(), txtApellidoFutbolista.getText(), Integer.parseInt(txtEdadFutbolista.getText()), Integer.parseInt(txtDorsalFutbolista.getText()), txtDemarcacionFutbolista.getText());
        
    }
    
    public boolean vacioTxtfutbolista(){
        boolean booleano = true;
        if(  txtNombreFutbolista.getText().equals("") ||
            txtApellidoFutbolista.getText().equals("") ||
            txtEdadFutbolista.getText().equals("") ||
            txtDorsalFutbolista.getText().equals("") ||
            txtDemarcacionFutbolista.getText().equals("")){
            
            if ( txtNombreFutbolista.getText().equals("")) txtNombreFutbolista.requestFocus();
            else if ( txtApellidoFutbolista.getText().equals("")) txtApellidoFutbolista.requestFocus();
            else if ( txtEdadFutbolista.getText().equals("")) txtEdadFutbolista.requestFocus();
            else if ( txtDemarcacionFutbolista.getText().equals("")) txtDemarcacionFutbolista.requestFocus();
            else if ( txtDorsalFutbolista.getText().equals("")) txtDorsalFutbolista.requestFocus();
            
            JOptionPane.showMessageDialog(ventana.this, "FALTO RELLENAR UN CAMPO", "CAMPO VACIO", JOptionPane.ERROR_MESSAGE);
            booleano = false;
        }
        
        return booleano;
        
    }
    
    private void btnAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJugadorActionPerformed
        // TODO add your handling code here:
        if ( btnAgregarJugador.getText().equals("GUARDAR")){
            
            if ( vacioTxtfutbolista() ){
                insertarFutbolista();
                for ( int i = 0; i < lstmodel.getSize(); i++ ){
                
                    if ( (Fut.getApellido().trim()+", "+ Fut.getNombre().trim()).equals(lstmodel.getElementAt( i ))){

                        JOptionPane.showMessageDialog(ventana.this, "Nombres y apellidos iguales, ingrese de otros datos");
                        return;

                    }

                }
                
                        
                lstmodel.addElement(Fut.getApellido()+", "+Fut.getNombre());

                txtNombreFutbolista.setText("");
                txtApellidoFutbolista.setText("");
                txtEdadFutbolista.setText("");
                txtDorsalFutbolista.setText("");
                txtDemarcacionFutbolista.setText("");
            
                txtNombreFutbolista.setEditable(false);
                txtApellidoFutbolista.setEditable(false);
                txtEdadFutbolista.setEditable(false);
                txtDorsalFutbolista.setEditable(false);
                txtDemarcacionFutbolista.setEditable(false);
                txtNombreFutbolista.setEditable(false);
                
                
                btnModificarJugador.setEnabled(true);
                btnEliminarJugador.setEnabled(true);
                
                btnAgregarJugador.setText("AGREGAR");
                
            }
            
        }else{
            
            btnAgregarJugador.setText("GUARDAR");
            txtNombreFutbolista.setEditable(true);
            txtApellidoFutbolista.setEditable(true);
            txtEdadFutbolista.setEditable(true);
            txtDorsalFutbolista.setEditable(true);
            txtDemarcacionFutbolista.setEditable(true);
            txtNombreFutbolista.setEditable(true);
            txtNombreFutbolista.requestFocus();
            
            btnModificarJugador.setEnabled(false);
            btnEliminarJugador.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnAgregarJugadorActionPerformed

    private void btnModificarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarJugadorActionPerformed
        // TODO add your handling code here:
        
        Futbolista futbolista_modificado;
        
        if ( btnModificarJugador.getText().equals("GUARDAR") ){
            futbolista_modificado = new Futbolista(Futbolista.id+1, txtNombreFutbolista.getText(), txtApellidoFutbolista.getText(), Integer.parseInt(txtEdadFutbolista.getText()), Integer.parseInt(txtDorsalFutbolista.getText()), txtDemarcacionFutbolista.getText());
            
            lstmodel.setElementAt(futbolista_modificado.getApellido()+", "+futbolista_modificado.getNombre(), Integer.parseInt(JOptionPane.showInputDialog("¿ingrese el numero de orden que quiere modificar?"))-1);
            
            txtNombreFutbolista.setText("");
            txtApellidoFutbolista.setText("");
            txtEdadFutbolista.setText("");
            txtDorsalFutbolista.setText("");
            txtDemarcacionFutbolista.setText("");
            
            txtApellidoFutbolista.setEditable(false);
            txtEdadFutbolista.setEditable(false);
            txtDorsalFutbolista.setEditable(false);
            txtDemarcacionFutbolista.setEditable(false);
            txtNombreFutbolista.setEditable(false);
            btnAgregarJugador.setEnabled(true);
            btnEliminarJugador.setEnabled(true);
            
            btnModificarJugador.setText("MODIFICAR");
           
        }else {
            btnAgregarJugador.setEnabled(false);
            btnEliminarJugador.setEnabled(false);
            txtNombreFutbolista.setEditable(true);
            txtApellidoFutbolista.setEditable(true);
            txtEdadFutbolista.setEditable(true);
            txtDorsalFutbolista.setEditable(true);
            txtDemarcacionFutbolista.setEditable(true);
            txtNombreFutbolista.setEditable(true);
            btnModificarJugador.setText("GUARDAR");
        }
        
    }//GEN-LAST:event_btnModificarJugadorActionPerformed

    private void btnEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJugadorActionPerformed
        // TODO add your handling code here:
        lstmodel.remove(Integer.parseInt(JOptionPane.showInputDialog("¿ingrese el numero de orden que quiere eliminar?"))-1);
    }//GEN-LAST:event_btnEliminarJugadorActionPerformed

    private void txtNombreEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEntrenadorActionPerformed

    private void txtAgregarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgregarViajeActionPerformed

    private void btnViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajeActionPerformed
        // TODO add your handling code here:
        if ( btnViaje.getText().equals("GUARDAR") ){
            
            cbViajes.addItem(txtAgregarViaje.getText());
            txtAgregarViaje.setText("");

            txtAgregarViaje.setEditable(false);
            
            btnViaje.setText("AGREGAR VIAJE");
            
        }else {
            
            txtAgregarViaje.setEditable(true);
            
            txtAgregarViaje.requestFocus();
            
            btnViaje.setText("GUARDAR");
            
        }
    }//GEN-LAST:event_btnViajeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String mensaje = String.format( "el jugador %s, tiene como entrenador a %s, "
                + "le toca el masaje con %s y debe viajar a %s", lstmodel.getElementAt(txtAJugador.getSelectedIndex()), 
                cbEntrenador.getSelectedItem(), cbMasajista.getSelectedItem(), cbViajes.getSelectedItem());
        
        JOptionPane.showMessageDialog(ventana.this, mensaje);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txtApellidoFutbolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoFutbolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoFutbolistaActionPerformed

    private void txtNombreMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMasajistaActionPerformed

    private void txtApellidoEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoEntrenadorActionPerformed

    
    
    private void btnModificarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEntrenadorActionPerformed
        // TODO add your handling code here:
        String listaEntrenador [ ] = new String[cbEntrenador.getItemCount()];;
        if ( btnModificarEntrenador.getText().equals("GUARDAR")){
            
            Entrenador entrenador_modificar = new Entrenador(txtIdFederacion.getText(), 1, txtNombreEntrenador.getText(), txtApellidoEntrenador.getText(), Integer.parseInt(txtEdadEntrenador.getText()));
            
            for(int i = 0; i < cbEntrenador.getItemCount(); i++){
                
                listaEntrenador[i]=cbEntrenador.getItemAt(i).toString();
                
            }
           
            listaEntrenador[Integer.parseInt(JOptionPane.showInputDialog("Ingrese el orden a modificar"))-1]=entrenador_modificar.getApellido()+", "+entrenador_modificar.getNombre();
            
            cbEntrenador.removeAllItems();
            
            for(int i = 0; i < listaEntrenador.length; i++){
                
                cbEntrenador.addItem(listaEntrenador[i]);
                
            }
            
            txtNombreEntrenador.setText("");
            txtNombreEntrenador.setText("");
            txtApellidoEntrenador.setText("");
            txtEdadEntrenador.setText("");
            txtIdFederacion.setText("");
            
            txtNombreEntrenador.setEditable(false);
            txtNombreEntrenador.setEditable(false);
            txtNombreEntrenador.setEditable(false);
            txtApellidoEntrenador.setEditable(false);
            txtEdadEntrenador.setEditable(false);
            txtIdFederacion.setEditable(false);
            txtNombreEntrenador.setEditable(false);
            txtNombreEntrenador.requestFocus();
            
            btnAgregarEntrenador.setEnabled(true);
            btnEliminarEntrenador.setEnabled(true);
            
            btnModificarEntrenador.setText("MODIFICAR");
            
        }else {
            
            btnModificarEntrenador.setText("GUARDAR");
            
            txtNombreEntrenador.setEditable(true);
            txtNombreEntrenador.setEditable(true);
            txtApellidoEntrenador.setEditable(true);
            txtEdadEntrenador.setEditable(true);
            txtIdFederacion.setEditable(true);
            txtNombreEntrenador.setEditable(true);
            txtNombreEntrenador.requestFocus();
            
            btnAgregarEntrenador.setEnabled(false);
            btnEliminarEntrenador.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_btnModificarEntrenadorActionPerformed

    public void insertarEntrenador(){
        
        ent = new Entrenador(txtIdFederacion.getText(), 1, txtNombreEntrenador.getText(), txtApellidoEntrenador.getText(), Integer.parseInt(txtEdadEntrenador.getText()));
       
    }
    public boolean vacioEntrenador(){
        boolean booleano = true;
        if ( txtNombreEntrenador.getText().equals("")|| 
             txtApellidoEntrenador.getText().equals("") || 
             txtEdadEntrenador.getText().equals("") || 
             txtIdFederacion.getText().equals("")){
            
            if( txtNombreEntrenador.getText().equals("") ) txtNombreEntrenador.requestFocus();
            else if( txtApellidoEntrenador.getText().equals("") ) txtApellidoEntrenador.requestFocus();
            else if( txtEdadEntrenador.getText().equals("") ) txtEdadEntrenador.requestFocus();
            else if( txtIdFederacion.getText().equals("") ) txtIdFederacion.requestFocus();
            
            JOptionPane.showMessageDialog(ventana.this, "FALTA LLENAR ALGUNOS CAMPOS" ,"CAMPO VACÍO", JOptionPane.ERROR_MESSAGE);
            booleano = false;
        }
        return booleano;
        
    }
    private void btnAgregarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEntrenadorActionPerformed
        // TODO add your handling code here:
        
        if ( btnAgregarEntrenador.getText().equals("GUARDAR") ){
            
            if( vacioEntrenador() ){
                insertarEntrenador();
                for ( int i = 0; i < cbEntrenador.getItemCount(); i++ ){
                    if ( cbEntrenador.getItemAt(i).equals((ent.getApellido().trim()+", "+ent.getNombre().trim())) ){
                        
                        JOptionPane.showMessageDialog(ventana.this, "NOMBRE Y APELLIDOS IGUALES, RELLENE OTROS CAMPOS");
                        return ;
                        
                    }
                }
                cbEntrenador.addItem(ent.getApellido()+", "+ent.getNombre());

                txtNombreEntrenador.setText("");
                txtApellidoEntrenador.setText("");
                txtEdadEntrenador.setText("");
                txtIdFederacion.setText("");

                txtNombreEntrenador.setEditable(false);
                txtNombreEntrenador.setEditable(false);
                txtApellidoEntrenador.setEditable(false);
                txtEdadEntrenador.setEditable(false);
                txtIdFederacion.setEditable(false);
                txtNombreEntrenador.setEditable(false);

                btnModificarEntrenador.setEnabled(true);
                btnEliminarEntrenador.setEnabled(true);
                btnAgregarEntrenador.setText("AGREGAR");
                
            }
            
        } else {
            
            btnAgregarEntrenador.setText("GUARDAR");
            
            txtNombreEntrenador.setEditable(true);
            txtNombreEntrenador.setEditable(true);
            txtApellidoEntrenador.setEditable(true);
            txtEdadEntrenador.setEditable(true);
            txtIdFederacion.setEditable(true);
            txtNombreEntrenador.setEditable(true);
            txtNombreEntrenador.requestFocus();
            
            btnModificarEntrenador.setEnabled(false);
            btnEliminarEntrenador.setEnabled(false);
            
        }
    }//GEN-LAST:event_btnAgregarEntrenadorActionPerformed

    private void btnEliminarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEntrenadorActionPerformed
        // TODO add your handling code here:
        
        String Nombre[ ] = new String[cbEntrenador.getItemCount()-1];
        
        int numero  = Integer.parseInt(JOptionPane.showInputDialog("ingrese orden a eliminar"));
        
        for ( int i = 0; i < Nombre.length ; i++ ){
            
            if ( (numero)-1 > i ) Nombre[i] = cbEntrenador.getItemAt(i);
            else Nombre[i] = cbEntrenador.getItemAt(i+1);
            
        }
        
        cbEntrenador.removeAllItems();
        
        for ( int i = 0; i < Nombre.length ; i++ ){
            
            cbEntrenador.addItem(Nombre[i]);
            
        }
        
    }//GEN-LAST:event_btnEliminarEntrenadorActionPerformed

    private void txtApellidoMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMasajistaActionPerformed

    private void btnModificarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMasajistaActionPerformed
        // TODO add your handling code here:
        String nombres_masajista[] = new String[cbMasajista.getItemCount()];
        
        if (btnModificarMasajista.getText().equals("GUARDAR")){
            
            Masajista modificar_masajista = new Masajista(txtTituloMasajista.getText(), Integer.parseInt(txtAniosExperiencia.getText()), 1, txtNombreMasajista.getText(), txtApellidoMasajista.getText(), Integer.parseInt(txtEdadMasajista.getText()));
            
            for (int i = 0; i < cbMasajista.getItemCount(); i++){

                nombres_masajista[i] = cbMasajista.getItemAt(i);

            } 
            int numero = Integer.parseInt(JOptionPane.showInputDialog("introduzca el numero a modificar"));
            
            nombres_masajista[numero-1] = modificar_masajista.getApellido().trim()+", "+modificar_masajista.getNombre().trim();
        
            cbMasajista.removeAllItems();
            
            for (String nombres_masajista1 : nombres_masajista) {
                cbMasajista.addItem(nombres_masajista1);
            }
            txtNombreMasajista.setText("");
            txtApellidoMasajista.setText("");
            txtEdadMasajista.setText("");
            txtTituloMasajista.setText("");
            txtAniosExperiencia.setText("");
            
            txtNombreMasajista.setEditable(false);
            txtApellidoMasajista.setEditable(false);
            txtEdadMasajista.setEditable(false);
            txtTituloMasajista.setEditable(false);
            txtAniosExperiencia.setEditable(false);
            
            btnEliminarMasajista.setEnabled(true);
            btnAgregarMasajista.setEnabled(true);
            btnModificarMasajista.setText("MODIFICAR");
        }else {
            
            txtNombreMasajista.setEditable(true);
            txtApellidoMasajista.setEditable(true);
            txtEdadMasajista.setEditable(true);
            txtTituloMasajista.setEditable(true);
            txtAniosExperiencia.setEditable(true);
            
            btnAgregarMasajista.setEnabled(false);
            btnEliminarMasajista.setEnabled(false);
            btnModificarMasajista.setText("GUARDAR");
            
        }
        
    }//GEN-LAST:event_btnModificarMasajistaActionPerformed

    public void datosMasajista(){
        Mas = new Masajista(txtTituloMasajista.getText(), Integer.parseInt(txtAniosExperiencia.getText()), 1, txtNombreMasajista.getText(), txtApellidoMasajista.getText(), Integer.parseInt(txtEdadMasajista.getText()));
    } 
    public boolean vacioMasajista(){
        
        if( txtNombreMasajista.getText().equals("") ||
            txtApellidoMasajista.getText().equals("")||
            txtEdadMasajista.getText().equals("") ||
            txtTituloMasajista.getText().equals("") ||
            txtAniosExperiencia.getText().equals("") ){
            
            if(txtNombreMasajista.getText().equals("")) txtNombreMasajista.requestFocus();
            else if(txtApellidoMasajista.getText().equals("")) txtApellidoMasajista.requestFocus();
            else if(txtEdadMasajista.getText().equals("")) txtEdadMasajista.requestFocus();
            else if(txtTituloMasajista.getText().equals("")) txtTituloMasajista.requestFocus();
            else if(txtAniosExperiencia.getText().equals("")) txtAniosExperiencia.requestFocus();
            
            JOptionPane.showMessageDialog(ventana.this, "FALTA INTRODUCIR ALGUNOS DATOS", "CAMPOS VACIOS", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }
            
    private void btnAgregarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMasajistaActionPerformed
        // TODO add your handling code here:
        if ( btnAgregarMasajista.getText().equals("GUARDAR") ){
            
            if(vacioMasajista()) return;
            datosMasajista();
            for ( int i = 0; i < cbMasajista.getItemCount(); i++){
                
                if ( cbMasajista.getItemAt(i).equals(Mas.getApellido().trim()+", "+Mas.getNombre().trim()) ){
                    
                    JOptionPane.showMessageDialog(ventana.this, "INGRESE OTROS DATOS", "DATOS EXISTENTES", JOptionPane.ERROR_MESSAGE);
                    return;
                    
                }
                
            }
            
            txtNombreMasajista.setText("");
            txtApellidoMasajista.setText("");
            txtEdadMasajista.setText("");
            txtTituloMasajista.setText("");
            txtAniosExperiencia.setText("");
            
            txtNombreMasajista.setEditable(false);
            txtApellidoMasajista.setEditable(false);
            txtEdadMasajista.setEditable(false);
            txtTituloMasajista.setEditable(false);
            txtAniosExperiencia.setEditable(false);
            
            btnModificarMasajista.setEnabled(true);
            btnEliminarMasajista.setEnabled(true);
            btnAgregarMasajista.setText("AGREGAR");
            
            cbMasajista.addItem(Mas.getApellido()+", "+Mas.getNombre());
            
        }else {
            
            txtNombreMasajista.setEditable(true);
            txtApellidoMasajista.setEditable(true);
            txtEdadMasajista.setEditable(true);
            txtTituloMasajista.setEditable(true);
            txtAniosExperiencia.setEditable(true);
            txtNombreMasajista.requestFocus();
            
            btnAgregarMasajista.setText("GUARDAR");
            
            btnEliminarMasajista.setEnabled(false);
            btnModificarMasajista.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_btnAgregarMasajistaActionPerformed

    private void btnEliminarMasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMasajistaActionPerformed
        // TODO add your handling code here:
        
        String eliminar[] = new String[cbMasajista.getItemCount()-1];
        int numero = Integer.parseInt(JOptionPane.showInputDialog(ventana.this, "INTRODUZCA EL ORDEN")) - 1;
        for ( int i = 0; i < eliminar.length; i++ ){
            
            if ( numero > i ) eliminar[i] = cbMasajista.getItemAt(i);
            else eliminar[i] = cbMasajista.getItemAt(i+1);
            
        }
        
        cbMasajista.removeAllItems();
        
        for (String eliminar1 : eliminar) {
            cbMasajista.addItem(eliminar1);
        }
        
    }//GEN-LAST:event_btnEliminarMasajistaActionPerformed

    private void txtAniosExperienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAniosExperienciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAniosExperienciaActionPerformed

    private void txtEdadFutbolistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadFutbolistaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if( Character.isLetter(validar) ){
            
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "solo numeros");
            
        }
    }//GEN-LAST:event_txtEdadFutbolistaKeyTyped

    private void txtNombreFutbolistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreFutbolistaKeyTyped
        // TODO add your handling code here:
        char evento = evt.getKeyChar();
        if(Character.isDigit(evento)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo letras");
        }
        
    }//GEN-LAST:event_txtNombreFutbolistaKeyTyped

    private void txtApellidoFutbolistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoFutbolistaKeyTyped
        // TODO add your handling code here:
        char evento = evt.getKeyChar();
        if(Character.isDigit(evento)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo letras");
        }
    }//GEN-LAST:event_txtApellidoFutbolistaKeyTyped

    private void txtDorsalFutbolistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDorsalFutbolistaKeyTyped
        // TODO add your handling code here:
        char evento = evt.getKeyChar();
        if(Character.isLetter(evento)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo numeros");
        }
    }//GEN-LAST:event_txtDorsalFutbolistaKeyTyped

    private void txtDemarcacionFutbolistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDemarcacionFutbolistaKeyTyped
        // TODO add your handling code here:
        char evento = evt.getKeyChar();
        if(Character.isDigit(evento)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo letras");
        }
    }//GEN-LAST:event_txtDemarcacionFutbolistaKeyTyped

    private void txtNombreEntrenadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEntrenadorKeyTyped
        // TODO add your handling code here:
        char evento = evt.getKeyChar();
        if(Character.isDigit(evento)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreEntrenadorKeyTyped

    private void sololetras(java.awt.event.KeyEvent evt){
        char evento = evt.getKeyChar();
        if(Character.isDigit(evento)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo letras");
        }
    }
    private void solonumeros(java.awt.event.KeyEvent evt){
        char evento = evt.getKeyChar();
        if(Character.isLetter(evento)){
            getToolkit().beep();
            evt.consume();
        }
    }
    
    private void txtApellidoEntrenadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoEntrenadorKeyTyped
        // TODO add your handling code here:
        char evento = evt.getKeyChar();
        if(Character.isDigit(evento)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoEntrenadorKeyTyped

    private void txtEdadEntrenadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadEntrenadorKeyTyped
        // TODO add your handling code here:
        solonumeros(evt);
    }//GEN-LAST:event_txtEdadEntrenadorKeyTyped

    private void txtIdFederacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFederacionKeyTyped
        // TODO add your handling code here:
        solonumeros(evt);
    }//GEN-LAST:event_txtIdFederacionKeyTyped

    private void txtNombreMasajistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreMasajistaKeyTyped
        // TODO add your handling code here:
        sololetras(evt);

    }//GEN-LAST:event_txtNombreMasajistaKeyTyped

    private void txtApellidoMasajistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMasajistaKeyTyped
        // TODO add your handling code here:
        sololetras(evt);

    }//GEN-LAST:event_txtApellidoMasajistaKeyTyped

    private void txtEdadMasajistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadMasajistaKeyTyped
        // TODO add your handling code here:
        solonumeros(evt);

    }//GEN-LAST:event_txtEdadMasajistaKeyTyped

    private void txtTituloMasajistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloMasajistaKeyTyped
        // TODO add your handling code here:
        sololetras(evt);

    }//GEN-LAST:event_txtTituloMasajistaKeyTyped

    private void txtAniosExperienciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAniosExperienciaKeyTyped
        // TODO add your handling code here:
        solonumeros(evt);

    }//GEN-LAST:event_txtAniosExperienciaKeyTyped

    private void txtAgregarViajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarViajeKeyTyped
        // TODO add your handling code here:
        sololetras(evt);

    }//GEN-LAST:event_txtAgregarViajeKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEntrenador;
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnAgregarMasajista;
    private javax.swing.JButton btnEliminarEntrenador;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnEliminarMasajista;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModificarEntrenador;
    private javax.swing.JButton btnModificarJugador;
    private javax.swing.JButton btnModificarMasajista;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnViaje;
    private javax.swing.JComboBox<String> cbEntrenador;
    private javax.swing.JComboBox<String> cbMasajista;
    private javax.swing.JComboBox<String> cbViajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JList<String> txtAJugador;
    private javax.swing.JTextField txtAgregarViaje;
    private javax.swing.JTextField txtAniosExperiencia;
    private javax.swing.JTextField txtApellidoEntrenador;
    private javax.swing.JTextField txtApellidoFutbolista;
    private javax.swing.JTextField txtApellidoMasajista;
    private javax.swing.JTextField txtDemarcacionFutbolista;
    private javax.swing.JTextField txtDorsalFutbolista;
    private javax.swing.JTextField txtEdadEntrenador;
    private javax.swing.JTextField txtEdadFutbolista;
    private javax.swing.JTextField txtEdadMasajista;
    private javax.swing.JTextField txtIdFederacion;
    private javax.swing.JTextField txtNombreEntrenador;
    private javax.swing.JTextField txtNombreFutbolista;
    private javax.swing.JTextField txtNombreMasajista;
    private javax.swing.JTextField txtTituloMasajista;
    // End of variables declaration//GEN-END:variables
}
