/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Usuario
 */

public class coleccionProductos extends javax.swing.JFrame {

    /**
     * Creates new form coleccionProductos
     */
    int fila;
    String []datos =  new String[4];
    arrayProducto lista = new arrayProducto(); 
    producto producto;
    DefaultTableModel modelo ;
    
    public coleccionProductos() {
        initComponents();
        
        estadoTextos(false);
        
        modelo =  new DefaultTableModel();
        
        modelo.addColumn("CODIGO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRECIO");
        modelo.addColumn("STOCK");
        
        tablaFacturacion.setModel(modelo);
    }

    public void estadoBotones(String btn, boolean valor){
        switch (btn) {
            case "AGREGAR":
                btnConsultar.setEnabled(valor);
                btnEliminar.setEnabled(valor);
                btnLimpiar.setEnabled(valor);
                btnModificar.setEnabled(valor);
                break;
            case "MODIFICAR":
                btnAgregar.setEnabled(valor);
                btnConsultar.setEnabled(valor);
                btnEliminar.setEnabled(valor);
                btnLimpiar.setEnabled(valor);
                break;
        }
    }
    public boolean unicoCodigo(){
        for (int i = 0; i < modelo.getRowCount(); i++){
            
            if(modelo.getValueAt(i, 0).equals(txtcodigo.getText())){
                return false;
            }
            
        }
        return true;
    }
    public boolean unicoCodigo(int j){
        for (int i = 0; i < modelo.getRowCount(); i++){
            
            if(i!=j){
                if(modelo.getValueAt(i, 0).equals(txtcodigo.getText())){
                    return false;
                }
            }
            
        }
        return true;
    }
    public boolean estaVacio(){
        return modelo.getRowCount() == 0;
    }
    public void estadoTextos(boolean valor){
        
        txtPrecio.setEditable(valor);
        txtStock.setEditable(valor);
        txtcodigo.setEditable(valor);
        txtdescripcion.setEditable(valor);
    }
    public void limpiarTextos(){
        txtPrecio.setText("");
        txtStock.setText("");
        txtcodigo.setText("");
        txtdescripcion.setText("");
    }
    public void crearProducto(){
        
        producto = new producto(txtcodigo.getText(), txtdescripcion.getText(), Float.parseFloat(txtPrecio.getText()), Integer.parseInt(txtStock.getText()));
        
    }
    public void crearArrayProducto(producto producto1){
        datos[0] = producto1.getCodigo();
        datos[1] = producto1.getDescripcion();
        datos[2] = Float.toString(producto1.getPrecio());
        datos[3] = Integer.toString(producto1.getStock());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturacion = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Descripcion:");

        jLabel4.setText("precio:");

        jLabel5.setText("Stock:");

        tablaFacturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION", "PRECIO", "STOCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFacturacion);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(txtStock)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addComponent(btnConsultar)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
        if ( btnAgregar.getText().equals("AGREGAR")){
            estadoTextos(true);
            estadoBotones(btnAgregar.getText(), false);
            btnAgregar.setText("GUARDAR");
        } else {
            
            if(!unicoCodigo()){
                JOptionPane.showMessageDialog(this, "inserte otro codigo");
                return;
            }
            
            crearProducto();
        
            lista.adicionar(producto);

            datos[0] = txtcodigo.getText();
            datos[1] = txtdescripcion.getText();
            datos[2] = txtPrecio.getText();
            datos[3] = txtStock.getText();

            modelo.addRow(datos);
            
            txtPrecio.setText("");
            txtStock.setText("");
            txtcodigo.setText("");
            txtdescripcion.setText("");
            
            btnAgregar.setText("AGREGAR");
            
            estadoTextos(false);
            estadoBotones(btnAgregar.getText(), true);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(estaVacio()) {
            JOptionPane.showMessageDialog(this, "esta vacio");
            return;
        }
        int i = Integer.parseInt(JOptionPane.showInputDialog("inserte la fila a eliminar")) - 1;
        lista.eliminar(i);
        modelo.removeRow(i);
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(estaVacio()) {
            JOptionPane.showMessageDialog(this, "esta vacio");
            return;
        }
        if( btnModificar.getText().equals("MODIFICAR")){
            
            estadoBotones(btnModificar.getText(), false);
            fila = Integer.parseInt(JOptionPane.showInputDialog("inserte la fila a modificar")) - 1;
            estadoTextos(true);
            producto = lista.consultar(fila);
        
            txtPrecio.setText(Float.toString(producto.getPrecio()));
            txtStock.setText(Integer.toString(producto.getStock()));
            txtcodigo.setText(producto.getCodigo());
            txtdescripcion.setText(producto.getDescripcion());
            
            btnModificar.setText("GUARDAR");
            
        } else {
            if(!unicoCodigo(fila)){
                JOptionPane.showMessageDialog(this, "inserte otro codigo");
                return;
            }
            crearProducto();
            crearArrayProducto(producto);
            
            lista.modificar(fila, producto);
            
            modelo.setValueAt(datos[0], fila, 0);
            modelo.setValueAt(datos[1], fila, 1);
            modelo.setValueAt(datos[2], fila, 2);
            modelo.setValueAt(datos[3], fila, 3);
            
            estadoTextos(false);
            limpiarTextos();
            
            btnModificar.setText("MODIFICAR");
            
            estadoBotones(btnModificar.getText(), true);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        if(estaVacio()) {
            JOptionPane.showMessageDialog(this, "esta vacio");
            return;
        }
        String consultar = (String) JOptionPane.showInputDialog(null, "seleccione categoria", "sistema de control de personal",JOptionPane.QUESTION_MESSAGE, null, new Object[]{"consultar","consultar por codigo", "cantidad producto","Mas caro","Mas barato"}, "1");
        
        switch (consultar) {
            case "consultar":
                
                break;
            case "consultar por codigo":
                String codigo = JOptionPane.showInputDialog("Escriba el codigo: ");
                producto = lista.consultarCodigo(codigo);
                JOptionPane.showMessageDialog(this, "Codigo: " + producto.getCodigo()+
                        "\nDescripcion: " + producto.getDescripcion()+
                        "\nPrecio: " + producto.getPrecio()+
                        "\nStock: " + producto.getStock());
                break;
            case "cantidad producto":
                JOptionPane.showMessageDialog(this, lista.cantidadProducto());
                break;
            case "Mas caro":
                producto = lista.Caro();
                JOptionPane.showMessageDialog(this, "Codigo: " + producto.getCodigo()+
                        "\nDescripcion: " + producto.getDescripcion()+
                        "\nPrecio: " + producto.getPrecio()+
                        "\nStock: " + producto.getStock());
                break;
            case "Mas barato":
                producto = lista.barato();
                JOptionPane.showMessageDialog(this, "Codigo: " + producto.getCodigo()+
                        "\nDescripcion: " + producto.getDescripcion()+
                        "\nPrecio: " + producto.getPrecio()+
                        "\nStock: " + producto.getStock());
                break;
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFacturacion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdescripcion;
    // End of variables declaration//GEN-END:variables
}
